### ISSUE TITLE
Getting accounts list with CLI fails both in legacy and non-legacy login

### ISSUE THREAD

**Issue by hogliux** [grindsa/dkb-robo#45]
I'm on version v0.23 and get the following error when using legacy login:

```sh
$ python3 dkb --debug -u xxxxxx -p xxxx --use-tan accounts 
DKBRobo._login()

DKBRobo._new_instance()

Starting new HTTPS connection (1): www.ib.dkb.de:443
https://www.ib.dkb.de:443 "GET /banking HTTP/1.1" 200 None
https://www.ib.dkb.de:443 "POST /banking HTTP/1.1" 200 None
DKBRobo._ctan_check()

Login failed: LinkNotFoundError
```
When using the non-legacy login, I get the following error:

```sh
$ python3 dkb --debug -u xxxxx -p xxxxx --use-tan accounts 
DKBRobo._login()

DKBRobo._new_session()

Starting new HTTPS connection (1): banking.dkb.de:443
https://banking.dkb.de:443 "GET /login HTTP/1.1" 200 None
DKBRobo._get_token()

https://banking.dkb.de:443 "POST /api/token HTTP/1.1" 200 None
DKBRobo._get_mfa_methods()

https://banking.dkb.de:443 "GET /api/mfa/mfa/methods?filter%5BmethodType%5D=seal_one HTTP/1.1" 200 None
_select_mfa_device()

Pick an authentication device from the below list:
[0] - DKB-App on XXXXX
[1] - DKB-App on XXXXX
[2] - DKB-App on XXXXX
:0
DKBRobo._process_userinput(0)
_select_mfa_device() ended with: 0
DKBRobo._get_mfa_challenge_id() login with device_num: 0

DKBRobo._get_mfa_challenge_id(): devicename: DKB-App on Google Pixel 4

https://banking.dkb.de:443 "POST /api/mfa/mfa/challenges HTTP/1.1" 201 None
DKBRobo._process_challenge_response()

DKBRobo._complete_2fa()

DKBRobo._print_2fa_confirmation()

check your banking app on "DKB-App on Google Pixel 4" and confirm login...
https://banking.dkb.de:443 "GET /api/mfa/mfa/challenges/xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx HTTP/1.1" 200 None
DKBRobo._check_processing_status()

DKBRobo._login: cnt 1 got processing flag
https://banking.dkb.de:443 "GET /api/mfa/mfa/challenges/xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx HTTP/1.1" 200 None
DKBRobo._check_processing_status()

DKBRobo._login: cnt 2 got processing flag
https://banking.dkb.de:443 "GET /api/mfa/mfa/challenges/xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx HTTP/1.1" 200 None
DKBRobo._check_processing_status()

DKBRobo._login: cnt 3 got processed flag
DKBRobo._update_token()

https://banking.dkb.de:443 "POST /api/token HTTP/1.1" 200 None
DKBRobo.get_portfolio()

https://banking.dkb.de:443 "GET /api/terms-consent/consent-requests??filter%5Bportfolio%5D=DKB HTTP/1.1" 400 None
https://banking.dkb.de:443 "GET /api/config/users/me/product-display-settings HTTP/1.1" 200 None
DKBRobo._get_accounts()

https://banking.dkb.de:443 "GET /api/accounts/accounts HTTP/1.1" 200 None
DKBRobo._get_cards()

https://banking.dkb.de:443 "GET /api/credit-card/cards?filter%5Btype%5D=creditCard&filter%5Bportfolio%5D=dkb&filter%5Btype%5D=debitCard HTTP/1.1" 200 None
DKBRobo._get_brokerage_accounts()

https://banking.dkb.de:443 "GET /api/broker/brokerage-accounts HTTP/1.1" 200 None
DKBRobo._get_loans()

https://banking.dkb.de:443 "GET /api/loans/loans HTTP/1.1" 200 None
DKBRobo._build_account_list()

DKBRobo._build_product_settings_dic()

DKBRobo._sort_product_group()

DKBRobo._get_account_details(65fad2ba-6e47-4343-ab57-43ab01446dd0)

DKBRobo._add_accountinformation()

DKBRobo._add_accountdetails()

DKBRobo._add_accountbalance()

DKBRobo._add_accountname()

DKBRobo._sort_product_group()

DKBRobo._get_account_details(01fdb729-4d04-4763-ab1b-c937a3132e70)

DKBRobo._add_accountinformation()

DKBRobo._add_accountdetails()

DKBRobo._add_accountbalance()

DKBRobo._add_accountname()

DKBRobo._get_brokerage_details(b45fb735-947e-3f6f-a213-c0452180a4f3)

DKBRobo._add_brokerageinformation()

DKBRobo._add_brokerage_performance()

DKBRobo._add_brokerageholder()

DKBRobo._do_sso_redirect()

https://banking.dkb.de:443 "POST /api/sso-redirect HTTP/1.1" 200 None
DKBRobo._new_instance()

_new_instance(): adding clientcookies.
DKBRobo._logout()

Starting new HTTPS connection (1): www.ib.dkb.de:443
https://www.ib.dkb.de:443 "GET /DkbTransactionBanking/banner.xhtml?$event=logout HTTP/1.1" 302 0
https://www.ib.dkb.de:443 "GET /logout.html HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/home/fr810/Developer/dkb-robo/dkb_robo/cli.py", line 220, in <module>
    main()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fr810/Developer/dkb-robo/dkb_robo/cli.py", line 76, in accounts
    del value["details"]
        ~~~~~^^^^^^^^^^^
KeyError: 'details'
```

**Comment by grindsa** [comment]
thank you for spotting this error. I forgot to adapt the CLI to the new UI.  This requires a bid of re-work to pls stay tuned...

**Comment by hogliux** [comment]
Thank you so much for your response. Indeed, when using `dkb_example.py`, I can get the accounts list. Thank you for this great tool!

**Comment by grindsa** [comment]
Fixed got released with [v0.23.1](https://github.com/grindsa/dkb-robo/releases/tag/0.23.1). `-t` parameter in CLI enforces the usage of legacy mode. Please give it a try and let me know if it works for you.

**Comment by hogliux** [comment]
I can now get the accounts list in both legacy and non-legacy mode. Thank you! Using `-t`/`--use-tan` still fails though (see issue #46)

**Comment by grindsa** [comment]
closing as the issue seems to be solved...
