### ISSUE TITLE
Why get transactions only for the last year?

### ISSUE THREAD

**Issue by kaztechSolutions** [grindsa/dkb-robo#48]
Hi,

in dkb_robo.py, inside the get_transactions function you call validate_dates and pass the value 3 in case of legacy_login, and value 1 in case of new login to the min_year parameter. Can you explain why? 

```
if self.legacy_login:
    (date_from, date_to) = validate_dates(self.logger, date_from, date_to, 3, self.legacy_login)
    transaction_list = self._legacy_get_transactions(transaction_url, atype, date_from, date_to, transaction_type)
else:
    (date_from, date_to) = validate_dates(self.logger, date_from, date_to, 1, self.legacy_login)
    transaction_list = self._get_transactions(transaction_url, atype, date_from, date_to, transaction_type)
```

I need to retrieve more than just one year, and if I change that parameter to a higher value, more that just one year is retrieved, meaning the API is supporting that. So, why do you limit that in the first place? 

Regards

**Comment by grindsa** [comment]
Hi,

the limitation does also exist in the new DKB-API (see below screenshot from the bottom of the transaction list)
![Capture](https://github.com/grindsa/dkb-robo/assets/12475288/e539d956-15cb-489d-b5fd-602b5742829c)

The corresponding rest call `'https://banking.dkb.de/api/accounts/accounts/<uid>/transactions` does always fetch the full transactions list of the last 360days and I use the `date_from` / `date_to` values for filtering only .

So the value 1 is mainly there for compatibility reasons and to auto-adjust `date_from`  in case its  are outside of the 1Y range.

HTH
G.

**Comment by BroderPeters** [comment]
The one-year limitation seems to be gone on the new UI. You can see the transactions until e.g. 2022 in the UI now as well. I was able to fetch the full year of 2023 by adjusting the code locally.
![image](https://github.com/user-attachments/assets/094b40ca-0f28-470a-913a-732bd20bb98d)


As the code change looks rather simple, I'm happy to open a PR for this.

**Comment by angelo-peronio** [comment]
@BroderPeters are you still interested in submitting the PR you mentioned?

Now that the old UI is gone (see #58), there is no way to fetch more than 1 year in the past with the current dkb-robo version 0.26.

Let me know if I can help in any way.

**Comment by grindsa** [comment]
I can look into it but not before the weekend.

Sorry
/G

**Comment by grindsa** [comment]
as @BroderPeters  indicated the code changes are rather simple and much easier than I thought. I pushed a couple of changes into the [devel branch](https://github.com/grindsa/acme2certifier/tree/devel) and got it working on my side.   Feel free to try and let me know if it works for you.

**Comment by angelo-peronio** [comment]
It does not seem to be working on my side.

I installed with

```
python -m pip install 'dkb-robo@git+https://github.com/grindsa/dkb-robo.git@devel'
```

Then tried

```
dkb --debug --username [redacted] --password [redacted] transactions --name [redacted] --date-from 2023-01-01
```
Obtaining, among the rest

```
validate_dates()
validate_dates(): adjust date_from to 12.09.2023
_enforce_date_format(): 12.09.2023, 11.09.2024 1
_convert_date_format(12.09.2023)
_convert_date_format(): cannot convert date: 12.09.2023
_convert_date_format() ended with: 2023-09-12
_convert_date_format(11.09.2024)
_convert_date_format(): cannot convert date: 11.09.2024
_convert_date_format() ended with: 2024-09-11
_enforce_date_format() ended with: 2023-09-12, 2024-09-11
validate_dates() returned: 2023-09-12, 2024-09-11
```

It seems that `date_from` still gets adjusted from 2023-01-01 to 2023-09-12, one year ago.
Am I missing something?

**Comment by angelo-peronio** [comment]
It works!

**Comment by BroderPeters** [comment]
Sorry for not getting back to it by the time, but great efforts from your side!

**Comment by grindsa** [comment]
extension got included in [v0.27](https://github.com/grindsa/dkb-robo/releases/tag/0.27). Hence i am closing the issue.
